# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "feature/jhow" ]
  pull_request:
    branches: [ "feature/jhow" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x     
    - run: npm install --save-dev cross-env   
    - run: npm install react
    - run: npm install react-dom
    - run: npm install --save gh-pages
    - run: npm install react-scripts
    
    - name: Set up Git user
      run: |
       git config --global user.name $user_name
       git config --global user.email $user_email
       git remote set-url origin https://${github_token}@github.com/${repository}
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        
    - name: Build
      run: npm run build
    
##  Deploy: 
##    runs-on: ubuntu-latest    
##    needs: build  
##    steps:
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        publish_dir: ./build
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

